import type { Metadata } from "next";
import "@/styles/globals.scss";
import Navhome from "@/components/navbar/Navhome";
import { I18nProvider } from "./i18n-provider";
import { ReduxProvider } from "@/store/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ReduxProvider>
          <I18nProvider>
            <main className="container">
              <Navhome />
              {children}
            </main>
          </I18nProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
